In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv(r'E:\credit card\fraudTest.CSV')

In [3]:
# first 5 rows of the dataset
credit_card_data.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [4]:
credit_card_data.tail()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
555714,555714,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,...,40.4931,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0
555715,555715,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,...,29.0393,-95.4401,28739,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0
555716,555716,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,...,46.1966,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0
555717,555717,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,...,44.6255,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0
555718,555718,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,...,35.6665,-97.4798,116001,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0

In [5]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             555719 non-null  int64
 1   trans_date_trans_time  555719 non-null  object
 2   cc_num                 555719 non-null  int64
 3   merchant               555719 non-null  object
 4   category               555719 non-null  object
 5   amt                    555719 non-null  float64
 6   first                  555719 non-null  object
 7   last                   555719 non-null  object
 8   gender                 555719 non-null  object
 9   street                 555719 non-null  object
 10  city                   555719 non-null  object
 11  state                  555719 non-null  object
 12  zip                    555719 non-null  int64
 13  lat                    555719 non-null  float64
 14  long                   555719 non-null  float64
 15  city_pop               555719 non-null  int64
 16  job                    555719 non-null  object
 17  dob                    555719 non-null  object
 18  trans_num              555719 non-null  object
 19  unix_time              555719 non-null  int64
 20  merch_lat              555719 non-null  float64
 21  merch_long             555719 non-null  float64
 22  is_fraud               555719 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 97.5+ MB

In [6]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [7]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['is_fraud'].value_counts()

is_fraud
0    553574
1      2145
Name: count, dtype: int64

In [8]:
##This Dataset is highly unblanced

#0 --> Normal Transaction

#1 --> fraudulent transaction

In [9]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.is_fraud == 0]
fraud = credit_card_data[credit_card_data.is_fraud == 1]

In [10]:
print(legit.shape)
print(fraud.shape)

(553574, 23)
(2145, 23)

In [11]:
# statistical measures of the data
legit.amt.describe()

count    553574.000000
mean         67.614408
std         152.471931
min           1.000000
25%           9.600000
50%          47.150000
75%          82.620000
max       22768.110000
Name: amt, dtype: float64

In [12]:
fraud.amt.describe()

count    2145.000000
mean      528.356494
std       392.747594
min         1.780000
25%       214.510000
50%       371.940000
75%       907.770000
max      1320.920000
Name: amt, dtype: float64

In [13]:
# compare the values for both transactions
credit_card_data['is_fraud'].value_counts()

is_fraud
0    553574
1      2145
Name: count, dtype: int64

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

In [14]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [15]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [16]:
new_dataset.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
260295,260295,2020-09-25 05:40:38,4440581794652,fraud_Kuhn LLC,misc_net,6.52,Karen,Cooper,F,425 Caleb Point Apt. 050,...,33.0067,-117.0690,1241364,"Pharmacist, hospital",1960-03-01,f801110d0aaa346079daba8e4aef9b00,1380087638,32.317485,-117.197402,0
446184,446184,2020-12-07 18:26:06,6535328428560433,fraud_Bednar PLC,kids_pets,73.44,Michelle,Beck,F,2887 Olson Road Suite 439,...,45.0632,-93.3811,1022298,Analytical chemist,1967-10-28,08d1336d915f235848962f0f04ced535,1386440766,44.792182,-94.164902,0
442381,442381,2020-12-07 04:07:18,6534628260579800,fraud_Prohaska-Murray,gas_transport,52.78,Christine,Harris,F,29606 Martinez Views Suite 653,...,44.3346,-73.0980,4542,Claims inspector/assessor,1998-03-19,f692628136223fe01ed10dfb51d3b6dc,1386389238,44.486062,-72.734719,0
352276,352276,2020-11-03 22:22:55,30135235368675,fraud_Ernser-Lynch,food_dining,59.68,Amanda,Williams,F,02018 Gary Key Apt. 911,...,39.1412,-94.3515,123373,"Engineer, production",1992-11-27,afd886fa99b6f8b1da310e8ea50511cf,1383517375,39.671710,-93.397296,0
523018,523018,2020-12-24 17:45:48,36913587729122,fraud_Schoen Ltd,kids_pets,82.72,Ana,Mccormick,F,4503 Patricia Route,...,43.6498,-116.4306,84106,Intelligence analyst,1971-02-11,95ed300c3a26be71b7617a58bfcc80ac,1387907148,44.200012,-116.191620,0

In [17]:
new_dataset.tail()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
517197,517197,2020-12-22 22:05:48,2242176657877538,"fraud_Willms, Kris and Bergnaum",shopping_pos,1041.51,Travis,Daniel,M,1327 Rose Causeway Apt. 610,...,34.6323,-89.8855,14462,Database administrator,1959-03-03,35b0297dd026d2e9a75d024a5dec7955,1387749948,34.573471,-89.911011,1
517274,517274,2020-12-22 22:18:07,2242176657877538,fraud_Kuhn LLC,shopping_pos,868.09,Travis,Daniel,M,1327 Rose Causeway Apt. 610,...,34.6323,-89.8855,14462,Database administrator,1959-03-03,da7f67d7375f10a054a3d919448c45dd,1387750687,34.091227,-90.390612,1
517341,517341,2020-12-22 22:31:48,2242176657877538,"fraud_Mosciski, Ziemann and Farrell",shopping_net,1039.42,Travis,Daniel,M,1327 Rose Causeway Apt. 610,...,34.6323,-89.8855,14462,Database administrator,1959-03-03,25b076c7bcd70f272c1c5326bb234f4b,1387751508,34.628434,-90.284780,1
517529,517529,2020-12-22 23:06:03,2242176657877538,fraud_Bauch-Raynor,grocery_pos,289.27,Travis,Daniel,M,1327 Rose Causeway Apt. 610,...,34.6323,-89.8855,14462,Database administrator,1959-03-03,2df7d894868fbc99ec1d8b055585fc9d,1387753563,34.746063,-90.401093,1
517571,517571,2020-12-22 23:13:39,2242176657877538,fraud_Jaskolski-Vandervort,misc_net,766.38,Travis,Daniel,M,1327 Rose Causeway Apt. 610,...,34.6323,-89.8855,14462,Database administrator,1959-03-03,44292cbc51e37dc018ee6a988a4bc426,1387754019,33.771462,-90.651342,1

In [18]:
new_dataset['is_fraud'].value_counts()

is_fraud
1    2145
0     492
Name: count, dtype: int64

In [34]:
new_dataset.groupby('is_fraud').value_counts()

is_fraud  Unnamed: 0  trans_date_trans_time  cc_num               merchant                             category      amt      first    last    gender  street                         city         state  zip    lat      long      city_pop  job                                  dob         trans_num                         unix_time   merch_lat  merch_long
0         65          2020-06-21 12:33:45    4509922033272157     fraud_Pouros-Haag                    shopping_pos  7.93     Monica   West    F       22084 Smith Roads Suite 776    Hurley       SD     57036  43.2893  -97.1904  811       Neurosurgeon                         1972-03-28  3aedf92246758786b01168d5dc5773b5  1371818025  43.795359  -96.833415    1
          3091        2020-06-22 08:20:32    341283058448499      fraud_Kiehn Inc                      grocery_pos   149.07   Mario    Johns   M       62130 Miller Square Suite 785  Brinson      GA     39825  30.9788  -84.7373  1461      Engineer, broadcasting (operations)  1935-09-08  7e1f1d7409aea6a512142ca992bbd35a  1371889232  31.391534  -84.305371    1
          4204        2020-06-22 14:50:48    342952484382519      fraud_O'Reilly, Mohr and Purdy       home          5.31     Kayla    Jones   F       6033 Young Track Suite 804     East Canaan  CT     6024   42.0158  -73.2913  647       Comptroller                          1987-09-26  26c1545f33f7ebb7ecab77770453f876  1371912648  42.380652  -73.322930    1
          4265        2020-06-22 15:08:48    4906628655840914250  fraud_Dickinson-Rempel               misc_pos      8.10     Charles  Moreno  M       838 Franklin Prairie Apt. 902  Key West     FL     33040  24.6557  -81.3824  32891     Town planner                         1987-02-13  39567c8e75665e151bae64ce8bfd9374  1371913728  23.914057  -80.946347    1
          5232        2020-06-22 19:44:01    6011652924285713     fraud_Kuhn LLC                       shopping_pos  7.03     Kathryn  Smith   F       19838 Tonya Prairie Apt. 947   Rocky Mount  MO     65072  38.2911  -92.7059  1847      Tax inspector                        1988-10-26  d94c348e301df55d83b5e7166e8dcb4a  1371930241  38.484506  -93.515303    1
                                                                                                                                                                                                                                                                                                                                                                     ..
1         517197      2020-12-22 22:05:48    2242176657877538     fraud_Willms, Kris and Bergnaum      shopping_pos  1041.51  Travis   Daniel  M       1327 Rose Causeway Apt. 610    Senatobia    MS     38668  34.6323  -89.8855  14462     Database administrator               1959-03-03  35b0297dd026d2e9a75d024a5dec7955  1387749948  34.573471  -89.911011    1
          517274      2020-12-22 22:18:07    2242176657877538     fraud_Kuhn LLC                       shopping_pos  868.09   Travis   Daniel  M       1327 Rose Causeway Apt. 610    Senatobia    MS     38668  34.6323  -89.8855  14462     Database administrator               1959-03-03  da7f67d7375f10a054a3d919448c45dd  1387750687  34.091227  -90.390612    1
          517341      2020-12-22 22:31:48    2242176657877538     fraud_Mosciski, Ziemann and Farrell  shopping_net  1039.42  Travis   Daniel  M       1327 Rose Causeway Apt. 610    Senatobia    MS     38668  34.6323  -89.8855  14462     Database administrator               1959-03-03  25b076c7bcd70f272c1c5326bb234f4b  1387751508  34.628434  -90.284780    1
          517529      2020-12-22 23:06:03    2242176657877538     fraud_Bauch-Raynor                   grocery_pos   289.27   Travis   Daniel  M       1327 Rose Causeway Apt. 610    Senatobia    MS     38668  34.6323  -89.8855  14462     Database administrator               1959-03-03  2df7d894868fbc99ec1d8b055585fc9d  1387753563  34.746063  -90.401093    1
          517571      2020-12-22 23:13:39    2242176657877538     fraud_Jaskolski-Vandervort           misc_net      766.38   Travis   Daniel  M       1327 Rose Causeway Apt. 610    Senatobia    MS     38668  34.6323  -89.8855  14462     Database administrator               1959-03-03  44292cbc51e37dc018ee6a988a4bc426  1387754019  33.771462  -90.651342    1
Name: count, Length: 2637, dtype: int64

Splitting the data into Features & Targets

In [35]:
X = new_dataset.drop(columns='is_fraud', axis=1)
Y = new_dataset['is_fraud']

In [36]:
print(X)

        Unnamed: 0 trans_date_trans_time            cc_num  \
260295      260295   2020-09-25 05:40:38     4440581794652
446184      446184   2020-12-07 18:26:06  6535328428560433
442381      442381   2020-12-07 04:07:18  6534628260579800
352276      352276   2020-11-03 22:22:55    30135235368675
523018      523018   2020-12-24 17:45:48    36913587729122
...            ...                   ...               ...
517197      517197   2020-12-22 22:05:48  2242176657877538
517274      517274   2020-12-22 22:18:07  2242176657877538
517341      517341   2020-12-22 22:31:48  2242176657877538
517529      517529   2020-12-22 23:06:03  2242176657877538
517571      517571   2020-12-22 23:13:39  2242176657877538

                                   merchant       category      amt  \
260295                       fraud_Kuhn LLC       misc_net     6.52
446184                     fraud_Bednar PLC      kids_pets    73.44
442381                fraud_Prohaska-Murray  gas_transport    52.78
352276                   fraud_Ernser-Lynch    food_dining    59.68
523018                     fraud_Schoen Ltd      kids_pets    82.72
...                                     ...            ...      ...
517197      fraud_Willms, Kris and Bergnaum   shopping_pos  1041.51
517274                       fraud_Kuhn LLC   shopping_pos   868.09
517341  fraud_Mosciski, Ziemann and Farrell   shopping_net  1039.42
517529                   fraud_Bauch-Raynor    grocery_pos   289.27
517571           fraud_Jaskolski-Vandervort       misc_net   766.38

            first       last gender                          street  ...  \
260295      Karen     Cooper      F        425 Caleb Point Apt. 050  ...
446184   Michelle       Beck      F       2887 Olson Road Suite 439  ...
442381  Christine     Harris      F  29606 Martinez Views Suite 653  ...
352276     Amanda   Williams      F         02018 Gary Key Apt. 911  ...
523018        Ana  Mccormick      F             4503 Patricia Route  ...
...           ...        ...    ...                             ...  ...
517197     Travis     Daniel      M     1327 Rose Causeway Apt. 610  ...
517274     Travis     Daniel      M     1327 Rose Causeway Apt. 610  ...
517341     Travis     Daniel      M     1327 Rose Causeway Apt. 610  ...
517529     Travis     Daniel      M     1327 Rose Causeway Apt. 610  ...
517571     Travis     Daniel      M     1327 Rose Causeway Apt. 610  ...

          zip      lat      long  city_pop                        job  \
260295  92128  33.0067 -117.0690   1241364       Pharmacist, hospital
446184  55428  45.0632  -93.3811   1022298         Analytical chemist
442381   5461  44.3346  -73.0980      4542  Claims inspector/assessor
352276  64058  39.1412  -94.3515    123373       Engineer, production
523018  83646  43.6498 -116.4306     84106       Intelligence analyst
...       ...      ...       ...       ...                        ...
517197  38668  34.6323  -89.8855     14462     Database administrator
517274  38668  34.6323  -89.8855     14462     Database administrator
517341  38668  34.6323  -89.8855     14462     Database administrator
517529  38668  34.6323  -89.8855     14462     Database administrator
517571  38668  34.6323  -89.8855     14462     Database administrator

               dob                         trans_num   unix_time  merch_lat  \
260295  1960-03-01  f801110d0aaa346079daba8e4aef9b00  1380087638  32.317485
446184  1967-10-28  08d1336d915f235848962f0f04ced535  1386440766  44.792182
442381  1998-03-19  f692628136223fe01ed10dfb51d3b6dc  1386389238  44.486062
352276  1992-11-27  afd886fa99b6f8b1da310e8ea50511cf  1383517375  39.671710
523018  1971-02-11  95ed300c3a26be71b7617a58bfcc80ac  1387907148  44.200012
...            ...                               ...         ...        ...
517197  1959-03-03  35b0297dd026d2e9a75d024a5dec7955  1387749948  34.573471
517274  1959-03-03  da7f67d7375f10a054a3d919448c45dd  1387750687  34.091227
517341  1959-03-03  25b076c7bcd70f272c1c5326bb234f4b  1387751508  34.628434
517529  1959-03-03  2df7d894868fbc99ec1d8b055585fc9d  1387753563  34.746063
517571  1959-03-03  44292cbc51e37dc018ee6a988a4bc426  1387754019  33.771462

        merch_long
260295 -117.197402
446184  -94.164902
442381  -72.734719
352276  -93.397296
523018 -116.191620
...            ...
517197  -89.911011
517274  -90.390612
517341  -90.284780
517529  -90.401093
517571  -90.651342

[2637 rows x 22 columns]

In [37]:
print(Y)

260295    0
446184    0
442381    0
352276    0
523018    0
         ..
517197    1
517274    1
517341    1
517529    1
517571    1
Name: is_fraud, Length: 2637, dtype: int64

Split the data into Training data & Testing Data

In [38]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [39]:
print(X.shape, X_train.shape, X_test.shape)

(2637, 22) (2109, 22) (528, 22)

# Model Training

Logistic Regression

In [40]:
model = LogisticRegression()

In [42]:
print(X_train.select_dtypes(include=['object']).columns)

Index(['trans_date_trans_time', 'merchant', 'category', 'first', 'last',
       'gender', 'street', 'city', 'state', 'job', 'dob', 'trans_num'],
      dtype='object')

In [43]:
X = credit_card_data.drop(
    columns=[
        'is_fraud',
        'trans_date_trans_time',
        'merchant',
        'category',
        'first',
        'last',
        'gender',
        'street',
        'city',
        'state',
        'job',
        'dob',
        'trans_num'
    ]
)

In [44]:
Y = credit_card_data['is_fraud']

In [45]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=2,
    stratify=Y
)

In [46]:
print(X_train.select_dtypes(include=['object']).columns)

Index([], dtype='object')

In [47]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, Y_train)

LogisticRegression(max_iter=1000)

In [48]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

LogisticRegression(max_iter=1000)

# Model Evaluation

Accuracy Score

In [49]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [50]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9961401338356858

In [51]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [52]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9961401425178147

In [53]:
import pickle

with open('fraud_model.pkl', 'wb') as f:
    pickle.dump(model, f)

print("Model saved successfully")

Model saved successfully